name: Deploy
on:
  push:
    branches:
      - master
      - develop

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID_DEV }}
  PUBLIC_URL: https://pool-beta.syfer.network
  S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME_DEV }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 16 ]
    steps:
      - uses: actions/checkout@v1
      - name: Handle environmental variables
        if: endsWith(github.ref, '/master')
        run: |
          echo "CLOUDFRONT_DISTRIBUTION_ID=${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}" >> $GITHUB_ENV
          echo "PUBLIC_URL=https://pool.syfer.network" >> $GITHUB_ENV
          echo "S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}" >> $GITHUB_ENV
      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install Packages
        run: npm ci
      - name: Deploy
        run: npm run aws:deploy
